name: Android Test

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: "Run UI Tests"
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            script: ./gradlew testDebugUnitTest connectedAndroidTest

      - uses: actions/upload-artifact@v2
        name: unit-test-reports
        with:
          name: unit-test-reports
          path: |
            ./app/build/reports